on: [push, pull_request]

name: ci

jobs:
  test_coverage:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo cmd setup-nightly
          cargo deny --help
          cargo llvm-cov --help
          cargo nextest --help
      - name: Lint
        run: cargo cmd lint
      - name: Test
        run: cargo cmd test-coverage-lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info

  test-macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo nextest --help
      - name: Test
        run: |
          cargo build
          cargo nextest run
